import "server-only";

import { z } from "zod";

import { ConfigurationError } from "./logging";

const schema = z.object({
  SUPABASE_URL: z.string().url(),
  SUPABASE_SERVICE_ROLE_KEY: z.string().min(20),
  PROFILE_ENCRYPTION_KEY: z.string().min(40),
  PROFILE_ENCRYPTION_KEY_VERSION: z.coerce.number().int().positive().default(1),
  SHARE_CODE_HMAC_KEY: z.string().min(32),
  OWNER_TOKEN_HMAC_KEY: z.string().min(32),
  RATE_LIMIT_HMAC_KEY: z.string().min(32),
  CRON_SECRET: z.string().min(24),
});

let cached: z.infer<typeof schema> | undefined;

/**
 * Reads server-only configuration. The dnastorage aliases are generated by the
 * Vercel/Supabase integration; standard names remain portable across hosts.
 */
export function env() {
  if (cached) return cached;

  const parsed = schema.safeParse({
    ...process.env,
    SUPABASE_URL:
      process.env.SUPABASE_URL ?? process.env.dnastorage_SUPABASE_URL,
    SUPABASE_SERVICE_ROLE_KEY:
      process.env.SUPABASE_SERVICE_ROLE_KEY ??
      process.env.dnastorage_SUPABASE_SERVICE_ROLE_KEY ??
      process.env.dnastorage_SUPABASE_SECRET_KEY,
  });

  if (!parsed.success) {
    const names = parsed.error.issues.map((issue) => issue.path.join("."));
    throw new ConfigurationError(`Server configuration invalid: ${names.join(", ")}`);
  }

  if (Buffer.from(parsed.data.PROFILE_ENCRYPTION_KEY, "base64").length !== 32) {
    throw new ConfigurationError(
      "PROFILE_ENCRYPTION_KEY must contain exactly 32 base64-encoded bytes.",
    );
  }

  cached = parsed.data;
  return cached;
}
