import "server-only";import {db} from "./supabase";import {decrypt,encrypt,hmac} from "./crypto";import {env} from "./env";import type {ProfilePayload,ShareMode} from "@/lib/quiz/types";
type Row={id:string;owner_token_hash:string;share_code_hash:string;payload_ciphertext:string;payload_iv:string;payload_auth_tag:string;share_mode:ShareMode;expires_at:string;quiz_version:string};
const decode=(row:Row)=>decrypt<ProfilePayload>({ciphertext:row.payload_ciphertext,iv:row.payload_iv,authTag:row.payload_auth_tag},env().PROFILE_ENCRYPTION_KEY);
export async function createStoredProfile(owner:string,code:string,payload:ProfilePayload,expires:string){const e=env(),sealed=encrypt(payload,e.PROFILE_ENCRYPTION_KEY);const {data,error}=await db().from("quiz_profiles").insert({owner_token_hash:hmac(owner,e.OWNER_TOKEN_HMAC_KEY),share_code_hash:hmac(code,e.SHARE_CODE_HMAC_KEY),payload_ciphertext:sealed.ciphertext,payload_iv:sealed.iv,payload_auth_tag:sealed.authTag,encryption_key_version:e.PROFILE_ENCRYPTION_KEY_VERSION,quiz_version:payload.quizVersion,share_mode:payload.shareMode,consent_version:"2026.1",expires_at:expires}).select().single();if(error)throw error;return data as Row}
export async function byOwner(owner:string){const e=env();const {data,error}=await db().from("quiz_profiles").select("*").eq("owner_token_hash",hmac(owner,e.OWNER_TOKEN_HMAC_KEY)).is("revoked_at",null).gt("expires_at",new Date().toISOString()).maybeSingle();if(error)throw error;return data?{row:data as Row,payload:decode(data as Row)}:null}
export async function byCode(code:string){const e=env();const {data,error}=await db().from("quiz_profiles").select("*").eq("share_code_hash",hmac(code,e.SHARE_CODE_HMAC_KEY)).is("revoked_at",null).gt("expires_at",new Date().toISOString()).maybeSingle();if(error)throw error;return data?{row:data as Row,payload:decode(data as Row)}:null}
export async function removeOwner(owner:string){const e=env();const {error}=await db().from("quiz_profiles").delete().eq("owner_token_hash",hmac(owner,e.OWNER_TOKEN_HMAC_KEY));if(error)throw error}
export async function setShareMode(owner:string,mode:ShareMode){const current=await byOwner(owner);if(!current)return false;const e=env(),payload={...current.payload,shareMode:mode},sealed=encrypt(payload,e.PROFILE_ENCRYPTION_KEY);const {error}=await db().from("quiz_profiles").update({share_mode:mode,payload_ciphertext:sealed.ciphertext,payload_iv:sealed.iv,payload_auth_tag:sealed.authTag}).eq("id",current.row.id);if(error)throw error;return true}

export async function purgeExpired(){const {count,error}=await db().from("quiz_profiles").delete({count:"exact"}).lte("expires_at",new Date().toISOString());if(error)throw error;return count??0}
